-- Об'єднання журналу ОСББ і Складу в один Supabase-проєкт (липень 2026).
-- Виконати ОДИН РАЗ у проєкті складу (vkwkyhjjjmcpmiakxohw) -- Dashboard -> SQL Editor.
-- На вже об'єднаному проєкті (де ці таблиці вже є) скрипт безпечний для
-- повторного запуску: усі create table/policy/function йдуть через
-- if not exists / or replace.
--
-- Це чиста DDL-міграція. Самі дані (записи schedule/garbage/dispatcher/chat/
-- photos, PIN-хеші, файли фото) переносились окремо і в цьому файлі не
-- відтворюються -- якщо розгортаєте на новому проєкті з нуля, дані журналу
-- доведеться або відновити з бекапу, або журнал стартує порожнім.
--
-- Таблиці app_auth / app_pin_attempts / telegram_config журналу навмисно
-- НЕ перевикористовують однойменні таблиці складу (інша форма даних -- у
-- журналу два PIN-и (lock/reset), у складу один) -- тому префікс osbb_.

create extension if not exists pgcrypto with schema extensions;

-- ── Доменні таблиці журналу (та сама форма, що й у видаленому проєкті) ─────
create table if not exists schedule (
  month_key text primary key,
  data jsonb not null default '{}'::jsonb
);

create table if not exists garbage (
  month_key text primary key,
  data jsonb not null default '{}'::jsonb
);

create table if not exists dispatcher (
  month_key text primary key,
  data jsonb
);

create table if not exists chat (
  id bigint generated by default as identity primary key,
  author text not null default 'Анонім',
  text text not null,
  created_at timestamptz default now()
);

create table if not exists photos (
  id uuid primary key default gen_random_uuid(),
  month_key text not null,
  day integer not null,
  role text not null,
  url text not null,
  created_at timestamptz default now()
);

-- ── Auth/config таблиці журналу, з префіксом osbb_ ──────────────────────────
create table if not exists osbb_app_auth (
  id int primary key default 1,
  lock_pin_hash text not null,
  reset_pin_hash text not null,
  constraint osbb_app_auth_single_row check (id = 1)
);

create table if not exists osbb_app_pin_attempts (
  pin_name text primary key,
  failed_count int not null default 0,
  locked_until timestamptz,
  last_failed_at timestamptz not null default now()
);

-- Тільки chat_id: bot_token спільний з уже існуючою telegram_config складу
-- (перевірено -- той самий бот) -- секрет не дублюється у другу таблицю.
create table if not exists osbb_telegram_config (
  id int primary key default 1,
  chat_id text not null,
  constraint osbb_telegram_config_single_row check (id = 1)
);

-- ── RLS ──────────────────────────────────────────────────────────────────
alter table schedule enable row level security;
alter table garbage enable row level security;
alter table dispatcher enable row level security;
alter table chat enable row level security;
alter table photos enable row level security;
alter table osbb_app_auth enable row level security;
alter table osbb_app_pin_attempts enable row level security;
alter table osbb_telegram_config enable row level security;
-- osbb_app_auth / osbb_app_pin_attempts / osbb_telegram_config НЕ отримують
-- жодної policy -- default-deny для anon/authenticated, доступ лише через
-- SECURITY DEFINER функції нижче. Це навмисно закриває діру, яку мав старий
-- проєкт журналу: там telegram_config був читабельний anon-ключем (токен
-- бота фактично публічний). Тут еквівалентна таблиця закрита з самого початку.

drop policy if exists "select all" on schedule;
drop policy if exists "insert all" on schedule;
drop policy if exists "update all" on schedule;
create policy "select all" on schedule for select to anon, authenticated using (true);
create policy "insert all" on schedule for insert to anon, authenticated with check (true);
create policy "update all" on schedule for update to anon, authenticated using (true) with check (true);

drop policy if exists "select all" on garbage;
drop policy if exists "insert all" on garbage;
drop policy if exists "update all" on garbage;
create policy "select all" on garbage for select to anon, authenticated using (true);
create policy "insert all" on garbage for insert to anon, authenticated with check (true);
create policy "update all" on garbage for update to anon, authenticated using (true) with check (true);

drop policy if exists "select all" on dispatcher;
drop policy if exists "insert all" on dispatcher;
drop policy if exists "update all" on dispatcher;
create policy "select all" on dispatcher for select to anon, authenticated using (true);
create policy "insert all" on dispatcher for insert to anon, authenticated with check (true);
create policy "update all" on dispatcher for update to anon, authenticated using (true) with check (true);

drop policy if exists "select all" on chat;
drop policy if exists "insert all" on chat;
drop policy if exists "update all" on chat;
create policy "select all" on chat for select to anon, authenticated using (true);
create policy "insert all" on chat for insert to anon, authenticated with check (true);
create policy "update all" on chat for update to anon, authenticated using (true) with check (true);

drop policy if exists "select all" on photos;
drop policy if exists "insert all" on photos;
drop policy if exists "update all" on photos;
create policy "select all" on photos for select to anon, authenticated using (true);
create policy "insert all" on photos for insert to anon, authenticated with check (true);
create policy "update all" on photos for update to anon, authenticated using (true) with check (true);

-- ── RPC-функції (та сама поведінка, що й supabase/*.sql, тільки таблиці
-- перейменовані на osbb_app_auth/osbb_app_pin_attempts) ────────────────────
create or replace function verify_lock_pin(attempt text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  attempt_row osbb_app_pin_attempts%rowtype;
  ok boolean;
  next_failed_count int;
begin
  select * into attempt_row from osbb_app_pin_attempts where pin_name = 'lock';

  if attempt_row.locked_until is not null and attempt_row.locked_until > now() then
    return false;
  end if;

  select exists (
    select 1 from osbb_app_auth
    where id = 1 and lock_pin_hash = crypt(attempt, lock_pin_hash)
  ) into ok;

  if ok then
    delete from osbb_app_pin_attempts where pin_name = 'lock';
    return true;
  end if;

  next_failed_count := case
    when attempt_row.pin_name is null or attempt_row.last_failed_at < now() - interval '15 minutes' then 1
    else attempt_row.failed_count + 1
  end;

  insert into osbb_app_pin_attempts (pin_name, failed_count, locked_until, last_failed_at)
  values (
    'lock',
    next_failed_count,
    case when next_failed_count >= 5 then now() + interval '5 minutes' else null end,
    now()
  )
  on conflict (pin_name) do update
    set failed_count = excluded.failed_count,
        locked_until = excluded.locked_until,
        last_failed_at = excluded.last_failed_at;

  return false;
end;
$$;

create or replace function verify_reset_pin(attempt text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  attempt_row osbb_app_pin_attempts%rowtype;
  ok boolean;
  next_failed_count int;
begin
  select * into attempt_row from osbb_app_pin_attempts where pin_name = 'reset';

  if attempt_row.locked_until is not null and attempt_row.locked_until > now() then
    return false;
  end if;

  select exists (
    select 1 from osbb_app_auth
    where id = 1 and reset_pin_hash = crypt(attempt, reset_pin_hash)
  ) into ok;

  if ok then
    delete from osbb_app_pin_attempts where pin_name = 'reset';
    return true;
  end if;

  next_failed_count := case
    when attempt_row.pin_name is null or attempt_row.last_failed_at < now() - interval '15 minutes' then 1
    else attempt_row.failed_count + 1
  end;

  insert into osbb_app_pin_attempts (pin_name, failed_count, locked_until, last_failed_at)
  values (
    'reset',
    next_failed_count,
    case when next_failed_count >= 5 then now() + interval '5 minutes' else null end,
    now()
  )
  on conflict (pin_name) do update
    set failed_count = excluded.failed_count,
        locked_until = excluded.locked_until,
        last_failed_at = excluded.last_failed_at;

  return false;
end;
$$;

create or replace function reset_month(table_name text, p_month_key text, attempt text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  ok boolean;
begin
  select verify_reset_pin(attempt) into ok;
  if not ok then
    return false;
  end if;

  if table_name = 'schedule' then
    delete from schedule where month_key = p_month_key;
  elsif table_name = 'garbage' then
    delete from garbage where month_key = p_month_key;
  elsif table_name = 'dispatcher' then
    delete from dispatcher where month_key = p_month_key;
  else
    raise exception 'invalid table_name: %', table_name;
  end if;

  return true;
end;
$$;

create or replace function delete_chat_message(p_message_id bigint, attempt text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  ok boolean;
begin
  select verify_reset_pin(attempt) into ok;
  if not ok then
    return false;
  end if;

  delete from chat where id = p_message_id;
  return true;
end;
$$;

create or replace function delete_photo(p_photo_id bigint, attempt text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  ok boolean;
begin
  select verify_reset_pin(attempt) into ok;
  if not ok then
    return false;
  end if;

  delete from photos where id = p_photo_id;
  return true;
end;
$$;

revoke all on function verify_lock_pin(text) from public;
revoke all on function verify_reset_pin(text) from public;
revoke all on function reset_month(text, text, text) from public;
revoke all on function delete_chat_message(bigint, text) from public;
revoke all on function delete_photo(bigint, text) from public;
grant execute on function verify_lock_pin(text) to anon, authenticated;
grant execute on function verify_reset_pin(text) to anon, authenticated;
grant execute on function reset_month(text, text, text) to anon, authenticated;
grant execute on function delete_chat_message(bigint, text) to anon, authenticated;
grant execute on function delete_photo(bigint, text) to anon, authenticated;

-- ── Telegram-сповіщення чату журналу: bot_token спільний з уже існуючою
-- telegram_config складу, chat_id -- з osbb_telegram_config. Заразом
-- виправляє реальний баг зі старого проєкту журналу: оригінальний
-- trg_notify_chat звертався до new.message, якої в таблиці chat не існує
-- (є тільки new.text) -- тому сповіщення чату там мовчки ніколи не йшли.
create or replace function notify_osbb_telegram(msg text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_token text;
  v_chat_id text;
begin
  select bot_token into v_token from telegram_config where id = 1;
  select chat_id into v_chat_id from osbb_telegram_config where id = 1;
  if v_token is null or v_chat_id is null then
    return;
  end if;

  perform net.http_post(
    url := 'https://api.telegram.org/bot' || v_token || '/sendMessage',
    body := jsonb_build_object('chat_id', v_chat_id, 'text', msg),
    headers := jsonb_build_object('Content-Type', 'application/json')
  );
exception when others then
  null;
end;
$$;

create or replace function trg_notify_chat()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform notify_osbb_telegram(
    '💬 Нове повідомлення в чаті ОСББ від ' || coalesce(new.author, 'Анонім') || ': ' || coalesce(new.text, '')
  );
  return new;
exception when others then
  return new;
end;
$$;

drop trigger if exists chat_telegram_notify on chat;
create trigger chat_telegram_notify after insert on chat for each row execute function trg_notify_chat();

-- ── Після виконання ──────────────────────────────────────────────────────
-- 1. Задати реальний PIN замість прикладових значень (INSERT в
--    osbb_app_auth з новими bcrypt-хешами lock_pin_hash/reset_pin_hash).
-- 2. Задати реальний chat_id в osbb_telegram_config (id=1), якщо
--    сповіщення чату журналу мають йти в інший Telegram-чат, ніж склад.
-- 3. Перевірити PIN-вхід журналу, скидання місяця, видалення фото/чату.
